# Generated by Django 4.2.7 on 2023-11-25 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='content',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='title',
        ),
    ]
